codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "setup.py"
  - "NiChart_DLMUSE/__main__.py"
  - "NiChart_DLMUSE/CalcROIVol.py"
  - "NiChart_DLMUSE/dlmuse_pipeline.py"
  - "NiChart_DLMUSE/MaskImage.py"
  - "NiChart_DLMUSE/RelabelROI.py"
  - "NiChart_DLMUSE/ReorientImage.py"
  - "NiChart_DLMUSE/SegmentImage.py"
